language: node_js
node_js:
  - "node"
notifications:
  email: false  
cache:
  directories:
    - node_modules
before-script:
  - npm install
script:
  - npm test
env:
  - SECRETKEY=randomsecretvalue
