language: node_js
node_js:
  - "node"
notifications:
  email: false  
cache:
  directories:
    - node_moduless
services:
  - postgresql
before-script:
  - npm install
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run setup-tables
script:
  - npm test
after_script:
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls


