language: node_js
node_js:
  - "node"
notifications:
  email: false  
cache:
  directories:
    - node_moduless
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'CREATE DATABASE epic_mail;' -U postgres
script:
  - npm test
after_script:
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls
deploy:
  provider: heroku
  api_key: 
    secure: 2c2041d0-6978-4cc6-94f3-a61bcfc45e6e
