language: node_js
node_js:
  - "node"
notifications:
  email: false  
cache:
  directories:
    - node_moduless
before-script:
  - npm install
script:
  - npm test
after_script:
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls


